### ISSUE TITLE
a bug with themes in settings

### ISSUE THREAD

**Issue by ivan123-ru** [revoltchat/revite#217]
after applying a theme in "Theme Shop" tab, i can't apply dark theme nor white theme in "Appearance" tab.
when i am trying to do that, i see this warning in dev console:
![image](https://user-images.githubusercontent.com/70339505/132893089-f72caf69-b9e3-451f-940e-812f25a83b2c.png)

**Comment by brecert** [comment]
I think is related to #65 

When a appearance setting is set by the user, it'll override the base underlying theme settings, similar overlaying it.

In this case when the Theme Shop applies a theme, it overrides the setting internally the same way a user would.
This makes it so that changing the base theme doesn't do anything because all the values have been overridden by the set theme.

A fix for this would be to make the Theme Shop themes applied as a "base" preset theme instead of the current way. 

You can reset your overrides by clicking the `Reset overrides` button in the advanced appearance settings to change between the default light and dark themes again.

**Comment by brecert** [comment]
This was fixed in #225
