### ISSUE TITLE
Open graph embed allowing javascript: protocol

### ISSUE THREAD

**Issue by isaqueks** [revoltchat/revite#252]
`javascript:` protocol is being allowed in open graph through `og:url` metadata. Example:  
`<meta property="og:url" content="javascript:alert('I am JavaScript running at ' + document.domain);" />`.  
There is the confirmation dialog, but if the user clicks "Continue", the JavaScript will be executed!
![image](https://user-images.githubusercontent.com/37017117/133700557-3ca350f6-fe4b-4994-81e4-1ecdcd7b9935.png)
![image](https://user-images.githubusercontent.com/37017117/133701274-e5e0767e-41cd-4f85-b520-ee9116764bc7.png)

Maybe only `http:`/`https:` protocols should be allowed?

**Comment by insertish** [comment]
Managed to recreate the issue.

![image](https://user-images.githubusercontent.com/38285861/133751175-f89ffc5b-5903-49b0-9ee3-8fe244a5fac0.png)

Adding `noreferrer` appears to prevent the running script from doing anything.

![image](https://user-images.githubusercontent.com/38285861/133751484-297796fb-3ee7-44ca-9416-04b0837c87c3.png)

I was considering adding a protocol whitelist but that would be a pain to maintain since there's a bunch of useful protocols such as `magnet:` and `mailto:` which are used commonly, I don't know whether it should be done anyways.

Should be fixed in 51f23f5aa0eedbda559d18fdd646ba56e3426c2e.
