### ISSUE TITLE
Specify that it's a new password when resetting password

### ISSUE THREAD

**Issue by brecert** [revoltchat/revite#273]
Currently when resetting a password the text will say `Enter your password` for the new password instead of specifying that it's a new password.

`Enter new password` or `Enter your new password` would better fit.

**Comment by LedaThemis** [comment]
The issue seems to be in
 https://github.com/revoltchat/revite/blob/12b97160433151c188b077bd3e85fc2ee35bbd99/src/context/intermediate/popovers/ModifyAccount.tsx#L113-L123
where the type specified (`password`), is used to target `login.enter.password` (currently is "Enter your password.")
https://github.com/revoltchat/revite/blob/12b97160433151c188b077bd3e85fc2ee35bbd99/src/pages/login/FormField.tsx#L34-L39

and in order to change the placeholder value, I assume that we need a new key (e.g. `new_password`) in the language JSON 

Are there any guidelines on creating new keys?

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
