### ISSUE TITLE
iOS15 safari cuts off message input field

### ISSUE THREAD

**Issue by ClaudiusSeibt** [revoltchat/revite#319]
The input field for messages is completely covered by the search bar in safari on iOS15
![image](https://user-images.githubusercontent.com/57871362/135351278-63557bac-397e-498d-b9d7-494a0d56acca.png)

**Comment by Nikegamerjjjj** [comment]
Hello i know about as i am using iPhone. As you know Apple added ability to change postion of adressbar(that bar wher you can write link to websites and search up), and it may close up input field. 

---

It works on mine(iPhone 8 Plus) by changing position back to top, instead of having the bar down. To change, on Safari press Aa button, and click to change position of bar to top. It can be done also on Settings app where you choose Safari and change there on.


Any questions? Just comment back.
;)

Nik

**Comment by insertish** [comment]
Can use https://developer.mozilla.org/en-US/docs/Web/CSS/env()

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
