### ISSUE TITLE
Mentioning user/channels in a message with existing tags keeps the @/# causing infinite repeat

### ISSUE THREAD

**Issue by Andre601** [revoltchat/revite#330]
When you write a message and tag either a user or channel in it will the icon used for the mention (`@`/`#`) stay after you selected the user/channel, causing the mention list to stay and every additional press of enter to select a new entry.

Video proof:
https://user-images.githubusercontent.com/11576465/136675141-0908b9c8-444e-43bd-9581-b099944a3afd.mp4

**Comment by Andre601** [comment]
Another issue I discovered.

Writing a text and then adding a mention **before** that text results in the mention being added to the end of the message and the `@`/`#` not being removed/replaced.

For example:
Writing a message like `How is your day?` and then adding an `@` at the start followed by selecting a user (e.g. insert) results in this text:
`@ How is your day?<@01EX2NCWQ0CHS3QJF0FEQS1GR4>`

My guess here is, that the logic behind setting the mention object seems to always put the text at the end and never where you actually used the `@` and also doesn't remove it when it is at the very end for some reason (tl;dr Broken replacement logic probably)

**Comment by LedaThemis** [comment]
So I've been playing with the auto complete system, and it seems that:

the first issue of repeated mention pop-up is caused by these lines of code:

https://github.com/revoltchat/revite/blob/12b97160433151c188b077bd3e85fc2ee35bbd99/src/components/common/AutoComplete.tsx#L83-L94
I assume the `j + 1` is because of the limit on emoji minimum query length (which is 2)
https://github.com/revoltchat/revite/blob/12b97160433151c188b077bd3e85fc2ee35bbd99/src/components/common/AutoComplete.tsx#L243-L250
https://github.com/revoltchat/revite/blob/12b97160433151c188b077bd3e85fc2ee35bbd99/src/components/common/AutoComplete.tsx#L251-L259

and the `index - 1` to offset the `j + 1`

that's why, when mentioning while there is text already before the mention, it would remove the character before the `#` or `@` while keeping the `#` or `@`, which causes the behavior in the video. (inserting a mention but keeping the `@`)

and that's also why it doesn't happen if the text is empty, because starting from the last character or the first character won't matter. (because length is equal to the whole text length)

as for the second issue, of mentions being inserted at the end:

it is also caused by the aforementioned lines of code, but it only happens when there are no query text in front of the `#` or `@`
which causes `index - 1` to be `-1`, and that causes `splice`, to cut from the end of the string.

which results in this behavior:

```md
<INSERT_MENTION>text ->  @tex<MENTION>
```
- it removes the last character (index `-1`) which is `t`
- it inserts the mention in index `-1`

Note that the mention query text **must** be empty. (or else it would work normally because `index - 1` would be positive)
