### ISSUE TITLE
Animated profile pictures only animate when hovering the first message sent by a author (while name/pfp is grouped)

### ISSUE THREAD

**Issue by the456gamer** [revoltchat/revite#338]
sorry for bad title
![image](https://user-images.githubusercontent.com/42748092/137318044-2c7f6f4f-c4bc-4687-941c-42eecf6ff6e1.png)

hovering over the first message (1) animates the profile picture (3), while hovering over the second image doesn't

<https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01F7ZSBSFHCAAJQ92ZGTY67HMN/01FHZ864BAGY3NARQ9NWCEEDFT>
messages used in example

**Comment by LedaThemis** [comment]
I can't really think of a way that won't change the way animating is currently handled, so if we're changing that, one option would be making the `MessageRenderer` hold values of whether a message is currently being hovered on or not.

It would be something like this

`MessageRenderer` would have an array that holds all messages rendered like below
```js
[
	{
		"message1": { "head": true, "hovering": false  },
		"message2": { "head": false, "hovering": false }
	},
	{
		"message3": { "head": true, "hovering": false },
                "message4": { "head": false, "hovering": true }
	}
]
```
in this example, `Message4` is currently being hovered on, to determine what avatar to animate, you call helper function `getCurrentHovering`, which:
1. finds the message that has `hovering` set to true
2. checks if message is `head` 
3. if it's `head`, `setCurrentAnimate` to the message id of message
4. if it's not `head`, get the `head` message, then `setCurrentAnimate` to message id of message

then each message render would get an `animate` boolean which is the value of evaluating whether `currentAnimate` is equal to the to-be-rendered message id

---
As for getting/making that array, for each message you:
1. check if it's head or not (which is currently implemented)
2. push it to a new object if it's `head`, and add it to last object if not
3. define `onMouseEnter` and `onMouseLeave`, that sets `hovering` of message in array.


I am not sure if this is optimal in terms of performance, because you are re-rendering each message component (currently rendered) on hover.

---
Another option would be to group messages with the same structure as above but in a container component, and trigger the animate effect depending on the container, which would pass it to the `head` message.
I think this would be better performance-wise

it would take above array and convert it to container components for each entry.
