### ISSUE TITLE
Flag issue and appearance

### ISSUE THREAD

**Issue by urynon** [revoltchat/revite#352]
**Issue - 1**

Current flag use for represent tamil language is incorrect and tamil people's land is south india. sri lanka flag suitable for sinhala/sinhalese language; so please update it to one of flags below,

https://en.wikipedia.org/wiki/Tamils

1 - option, india flag as usually use https://en.wikipedia.org/wiki/India
https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/800px-Flag_of_India.svg.png
2 - option, main tamil state flag/emblem https://en.wikipedia.org/wiki/File:..Tamil_Nadu_Flag(INDIA).png
https://en.wikipedia.org/wiki/Government_of_Tamil_Nadu
https://en.wikipedia.org/wiki/South_India

**Issue - 2**

If user enabled chrome dark mode through `chrome://flags --> force dark mode for web contents` then some flags appear with notable color difference, see screenshots below (around 5, 6 flags)

![image](https://user-images.githubusercontent.com/81799342/138552758-c615cee8-4ad3-4bd5-88b7-a6aff484b9d7.png)
![image](https://user-images.githubusercontent.com/81799342/138552770-8df224c2-d1e6-4587-a86b-e16a6767fd37.png)

**Comment by insertish** [comment]
## Issue 1

I can't apply the Tamil Nadu flag in the quick select but it'll appear in the languages menu. (no Unicode equivalent)

## Issue 2

Can't actually reproduce the specific issue on Chromium 92, but I can see it messing up other websites. Also marking this issue as invalid since it requires use of browser flags to reproduce.
