### ISSUE TITLE
add support for applying masquerades in-app

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revite#454]
things to consider:
- should we store previously used masquerades? 
  - maybe "favourite masquerades" that can easily be re-used?
- should masquerades be per-message or applied until the user manually disables them?

**Comment by onpon4** [comment]
Would like to give some input on how I think this should be implemented (as an avid user of PluralKit who's only not using Revolt because this important accessibility feature is missing):

* There needs to be a permanent list of masquerades or the functionality is useless (imagine having to re-enter your display name and re-choose your avatar every session, it would be entirely inaccessible). Ideally, the list should be stored server-side along with the account information.
* The mode for selecting what masquerade is used per message needs to be both persistent and allow quick changes. It seems to me that the simplest way to do this would be a simple selection drop-box type thing choosing the masquerade to use which is persistent throughout the session until you change it.
  * Slight complication to note: some systems have hundreds or even thousands of headmates. The selection box needs to account for this by having a search box at the very least, and a fast alternative to the selection box may be prudent as well. A fast alternative could be as simple as a slash-command that chooses a masquerade by some user-chosen identifier string, or as complicated as PK's prefix/suffix feature (where a message would get a different masquerade than the selected one if it has user-defined prefixes and/or suffixes).
* Possibly superfluous to note, but such a feature ought to work in DMs. Not working in DMs wouldn't make the feature any worse than PK on Discord, and there's a fairly easy workaround in the form of creating a dedicated "DM server" for everyone you message, but that's incredibly clunky and not ideal. I mention this because I don't know if the use-case of DMs has been considered in the development of the masquerades feature; if it hasn't and they can't be used in DMs, that ought to be corrected, especially because that would make the feature *better* than PK and not just equal to it.

🦇
