### ISSUE TITLE
bug: voice permissions are lost after reloading the app

### ISSUE THREAD

**Issue by insertish** [revoltchat/revite#459]
Hence user is re-prompted whenever entering settings.

**Comment by vertigo220** [comment]
Just tried testing this with a friend and we both had this issue. And it's not that the permissions are lost after reloading the app, but even exiting and reopening settings or just switching to a different page in settings and back and it shows that permissions need to be granted. Additionally, it doesn't give any indication that permissions are needed when trying to make a call, making it appear that it's just not working and requiring the user to dig into settings to discover this on their own.

When he tried calling me, it never rang and just showed him as being connected, so we thought maybe it doesn't actually call the other person but just open a line and the other person has to do the same on their end with no notification of an incoming call, so I clicked the call button thinking we would then be connected, but we weren't. That's when he saw the permissions issue in settings, but we should have received some sort of notification that necessary permissions were missing when attempting to make a call.

Due to this issue, it appears voice calling doesn't work at all.

**Comment by insertish** [comment]
Closing due to rewrite of both client and voice server, marking as potential issue in future by linking to https://github.com/revoltchat/vortex/issues/30.
