### ISSUE TITLE
[Feature Request] Show tooltips when hovering over emoji

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revite#494]
### What do you want to see?

The app should show a tooltip when hovering over emoji containing the emoji's name. In addition, maybe we could show a popup upon clicking on the emoji that shows a preview of it and (once custom emotes are added) whether the emoji is global or server specific?

### Commit hash

81af91fa1ffcd6e5433dee8a4c46d23636eaf0ff

### Branch

Nightly (nightly.revolt.chat)

### PWA

- [ ] Yes, this feature request is specific to the PWA.

**Comment by kuhnchris** [comment]
Base version using "title" attribute of <img>:
![image](https://user-images.githubusercontent.com/761911/148468252-1f344fc0-94d1-425d-97b4-31da64b18903.png)

We could implement a manual mouse-over - but this is being rendered as HTML albeit having a <Emoji> styled-component - probably because it is being rendered in the Markup?

**Comment by trashtemp** [comment]
We could just use the Tippy tooltip that we use all throughout the app - will take this into consideration of implementing it

**Comment by kuhnchris** [comment]
ok so you want me to close the PR and you want to handle it via Tippy or shall I rewrite it to use Tippy?

**Comment by kuhnchris** [comment]
as discussed on Revolt: Closed in flavor of implementing it yourself.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.
