### ISSUE TITLE
Icons don't load on older Safari versions due to lack of webp support

### ISSUE THREAD

**Issue by Shadowknight1104** [revoltchat/revite#500]
Devices running macOS Catalina or earlier (Even if Safari version is <14) do not support WebP for some reason. This causes the icons to not load and instead shows a "?".
![image](https://user-images.githubusercontent.com/74649727/148588462-5fdb52df-c858-44dd-8f00-789cd4178273.png)
![image](https://user-images.githubusercontent.com/74649727/148588471-4b576386-6084-4167-aa66-0c3294401d55.png)

A solution to this would be to have an alternate source(maybe jpegs?) for browser that don't support WebP.

**Comment by Rexogamer** [comment]
We've discussed this internally and have decided not to fix this. Safari on macOS pre Big Sur is very much an outlier in terms of WebP support, and we suspect that the number of people using Revolt on Safari on older versions of macOS is rather small and likely shrinking - unlike [that other <​OS> 11](https://www.microsoft.com/en-gb/windows/windows-11-specifications), Big Sur [isn't particularly strict in terms of device support](https://en.wikipedia.org/wiki/MacOS_Big_Sur#System_requirements) and seems to support every Mac released after 2015. In addition, it seems Chrome, Firefox and Edge all support WebP regardless of platform, so you could use one of those (or [Revolt Desktop](https://github.com/revoltchat/desktop/releases/v1.0.2)) instead of Safari. I appreciate this may be a disappointing response, but as we are a small team the work to mitigate this would likely outweigh the benefits. Have a great day, and thanks for using Revolt!
