### ISSUE TITLE
[Bug Report] External: Windows 11 is detected as 10

### ISSUE THREAD

**Issue by trehousecomicsDev** [revoltchat/revite#540]

**Comment by Rexogamer** [comment]
This is an issue with the platform/browser detection library we use - however, at its core, this is due to Microsoft not increasing the kernel version. You can see the relevant Revite code [here](https://github.com/revoltchat/revite/blob/master/src/pages/login/forms/FormLogin.tsx) - I've opened an issue with the relevant library (DamonOehlman/detect-browser#173), so hopefully, a solution of some kind can be found :)
