### ISSUE TITLE
Signup Confirmation URL always gives invalid token 

### ISSUE THREAD

**Issue by 4444dogs** [revoltchat/revite#725]
### What happened?

Same as title

Browser: Brave

### Branch

Production (app.revolt.chat)

### Commit hash

N/A

### What browsers are you seeing the problem on?

Other (please specify in the "What happened" form)

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

**Comment by bljmania** [comment]
What

**Comment by idbrii** [comment]
I just signed up and got this, but I guess due to #888 I shouldn't open an issue?

I got two emails, so the first email gave INVALIDTOKEN, but the second email worked. I'm not sure what triggered the second email.

I signed up by visiting https://revolt.chat/ clicking download, installing Android app from Play, opening, Sign up, tap app button to open my email, it opened the first email, tap Confirm. Went back to my email and saw there was another (identical) reply.

Also seems like this is the same issue as #442.
