### ISSUE TITLE
bug: image uploading stopped working

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [revoltchat/revite#940]
### What happened?

as of today at 18:29 GMT+1 i am unable to upload any screenshots to messages on revolt, i have tried reloading the desktop app, restarting the desktop app and signing out and back in and it has not fixed anything

i also noticed it happening on mobile as i was making the bug report

on desktop it is stuck at 0% and on mobile it says network error as if i’m not connected to the internet

### Branch

Production (app.revolt.chat)

### Commit hash

i am unable to copy this info as it won’t let me select anything in the bottom of the settings page

### What browsers are you seeing the problem on?

Microsoft Edge

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by DeclanChidlow** [comment]
Hi, thanks for the issue.
This is a known issue that is due to the file server (autumn) being down. We don't know when it will be up but we hope it'll be soon.

It may be worth joining the Revolt Lounge as it has a channel which will notify you of such things. https://rvlt.gg/JvfFejhw

**Comment by pinkjimrussiagirl** [comment]
> Hi, thanks for the issue. This is a known issue that is due to the file server (autumn) being down. We don't know when it will be up but we hope it'll be soon.
> 
> It may be worth joining the Revolt Lounge as it has a channel which will notify you of such things. https://rvlt.gg/JvfFejhw

ok, also i don’t like joining public servers because i get too many notifications and unreads

**Comment by Rexogamer** [comment]
You have repeatedly been asked to stop doing this. This is your ***final warning*** - please stop or we will remove your ability to interact with Revolt's repositories.

**Comment by pinkjimrussiagirl** [comment]
> Regarding the content removed from your comment:
> 
> You have repeatedly been asked to stop doing this. This is your _**final warning**_ - please stop or we will remove your ability to interact with Revolt's repositories.

**OK FINE AND PLEASE STOP STALKING ME OR I WILL BE LEAVING REVOLT AS WELL AND RETURNING BACK TO GUILDED OR DISCORD AND USE SOMETHING THAT WON’T BAN ME FROM CONTACTING SUPPORT**

**Comment by Rexogamer** [comment]
Nobody is stalking you. We have a public feed of all new GitHub issues/commits in our Revolt and Discord servers, and anyone can set up notifications for a public repo and new issues/comments. You are more than welcome to ask for help; however, you are consistently ignoring the requests of a team member to stop bringing up unrelated issues in random comments. 

Nobody has responded to your question because:
1. we do not have a solid answer for you
2. we're busy with much more pressing issues and 
3. it really isn't that urgent - you're asking us to drop everything and help you for a minor cosmetic request?

If this is your reaction to a friendly request to stop doing something - a request you have repeatedly been asked to abide by and have repeatedly ignored - I have serious doubts about your ability to interact with the project in a civil and constructive manner.
